In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame
import datetime
import os
import matplotlib.pyplot as plt
import regex
import re

In [15]:
R_data=pd.read_csv("D:/HE_Bounce_prediction/HE_approval_note/HE_customerdetails.csv")

In [3]:
Dict=pd.read_csv("D:/HL/Keywords_v2.csv",encoding = "ISO-8859-1")

In [6]:
Dict.shape

(856, 2)

In [5]:
Dict=Dict.drop_duplicates()

In [7]:
R_data.head()

                Lead.id                                    customerdetails
0  53f032d3-0830-4025-a  Applicant is running a tuition centre in the n...
1  246dfdcc-0f24-4f19-8   Profile wise, applicant is into fishering bus...
2  9c1b8078-d323-47d6-8  Customer is running a degree colleges by the n...
3  91d81bfe-953a-4667-8  \tCustomer is into whole sale trading of ladie...
4  4d39cb27-ba85-475d-a  Mr. Uday Dighe is into business of interior wo...

In [ ]:
# R_data[R_data['customer business'].isnull()]

In [ ]:
# R_data['business'] = R_data['Business Details'].str.cat(R_data['Business Profile'], sep =" ") 
# R_data['customer business']=R_data['business'].str.cat(R_data['Personal Details'], sep =" ")

In [8]:
### CONVERTING TO LOWER CASE
Dict['Key Words']=Dict['Key Words'].str.lower()

In [9]:
### Removing Punctuation
Dict['Key Words'] = Dict['Key Words'].str.replace('[^\w\s]','')
Dict['Key Words'].head()

0    manufacturing
1          trading
2             shop
3             milk
4           retail
Name: Key Words, dtype: object

In [10]:
### REMOVING UNWANTED SPACE
Dict['Key Words'] = Dict['Key Words'].replace('\s+', ' ', regex=True)
Dict['Key Words'].head()

0    manufacturing
1          trading
2             shop
3             milk
4           retail
Name: Key Words, dtype: object

In [11]:
### REMOVING UNWANTED SPACE
Dict['Key Words'] = Dict['Key Words'].replace('\s+', ' ', regex=True)
Dict['Key Words'].head()

0    manufacturing
1          trading
2             shop
3             milk
4           retail
Name: Key Words, dtype: object

In [12]:
L_Dict=Dict['Key Words'].tolist()

In [13]:
L_Dict

['manufacturing',
 'trading',
 'shop',
 'milk',
 'retail',
 'supply',
 'wholesale',
 'self',
 'material',
 'contractor',
 'building',
 'furniture',
 'daily',
 'service',
 'transport',
 'construction',
 'store',
 'gold',
 'electrical',
 'enterprises',
 'selling',
 'water',
 'hotel',
 'kirana',
 'machinery',
 'vegetable',
 'rented',
 'rental',
 'auto',
 'travels',
 'food',
 'silver',
 'dairy',
 'infrastructure',
 'stores',
 'tailoring',
 'fruit',
 'catering',
 'tea',
 'pan',
 'provision',
 'supplies',
 'rice',
 'vehicles',
 'garments',
 'stall',
 'flower',
 'supplier',
 'agriculture',
 'materials',
 'coconut',
 'steel',
 'embroidery',
 'vendor',
 'bricks',
 'wood',
 'civil',
 'mobile',
 'vegetables',
 'jewellery',
 'grocery',
 'diamond',
 'fabrication',
 'clinic',
 'painting',
 'ornaments',
 'trade',
 'chicken',
 'cloth',
 'dress',
 'sarees',
 'transportation',
 'saree',
 'beauty',
 'fancy',
 'interior',
 'fish',
 'chain',
 'industrial',
 'snacks',
 'textile',
 'scrap',
 'cement',
 'education',
 'traders',
 'plastic',
 'saloon',
 'tiles',
 'bakery',
 'plumbing',
 'hair',
 'power',
 'printing',
 'farm',
 'cutting',
 'repairing',
 'fast',
 'sand',
 'tailor',
 'driver',
 'mill',
 'restaurant',
 'cows',
 'call',
 'maligai',
 'oil',
 'iron',
 'spare',
 'mess',
 'stitching',
 'welding',
 'fruits',
 'paper',
 'readymade',
 'stone',
 'contractor',
 'motor',
 'parlour',
 'tours',
 'wooden',
 'photo',
 'silk',
 'textiles',
 'dealer',
 'carpenter',
 'sweets',
 'paddy',
 'studio',
 'merchant',
 'toursamp',
 'centring',
 'cotton',
 'metal',
 'bags',
 'fishing',
 'ice',
 'tiffin',
 'parlor',
 'hospital',
 'fruit',
 'plant',
 'designing',
 'fashion',
 'flour',
 'distribution',
 'travel',
 'builder',
 'mineral',
 'mutton',
 'books',
 'digital',
 'mechanic',
 'cloths',
 'electricals',
 'security',
 'tent',
 'glass',
 'railway',
 'brick',
 'cable',
 'decoration',
 'government',
 'computer',
 'cultivating',
 'lorry',
 'drinks',
 'marriage',
 'smith',
 'agent',
 'fisherman',
 'tractor',
 'electronics',
 'college',
 'sweet',
 'law',
 'manufacture',
 'operates',
 'pooja',
 'rickshaw',
 'training',
 'boat',
 'factory',
 'sand',
 'xerox',
 'consultancy',
 'farmer',
 'garment',
 'jcb',
 'ship',
 'buildings',
 'mobiles',
 'aluminum',
 'book',
 'polishing',
 'operator',
 'accessories',
 'aqua',
 'builders',
 'design',
 'foods',
 'stationery',
 'temple',
 'farming',
 'kovil',
 'builders',
 'electronic',
 'hotels',
 'garage',
 'marble',
 'nursry',
 'store',
 'coaching',
 'driving',
 'provisional',
 'kitchen',
 'sarees',
 'designer',
 'manpower',
 'corporation',
 'earth',
 'footwear',
 'road',
 'sound',
 'classes',
 'cycle',
 'dealers',
 'doctor',
 'insurance',
 'management',
 'manufacturing',
 'shoes',
 'trading',
 'cow',
 'cutting',
 'fmcg',
 'poultry',
 'software',
 'agro',
 'gift',
 'tools',
 'director',
 'priest',
 'trading',
 'wholeseller',
 'card',
 'installation',
 'juice',
 'shoe',
 'video',
 'gas',
 'electric',
 'export',
 'packing',
 'solutions',
 'educational',
 'fishermans',
 'institute',
 'masala',
 'repair',
 'teacher',
 'truck',
 'cleaning',
 'meat',
 'milk',
 'station',
 'trader',
 'banana',
 'boxes',
 'mart',
 'air',
 'bag',
 'hollow',
 'real',
 'servicing',
 'cool',
 'cream',
 'medicine',
 'packaging',
 'boutique',
 'canteen',
 'cows',
 'granite',
 'imitation',
 'mason',
 'retired',
 'sanitary',
 'contractor',
 'foot',
 'pipe',
 'plates',
 'stationary',
 'timber',
 'tyre',
 'washing',
 'dresses',
 'fabrics',
 'rubber',
 'tyres',
 'wholesaler',
 'flowers',
 'garments',
 'heavy',
 'hostel',
 'plywood',
 'snack',
 'tiffen',
 'engine',
 'godown',
 'powder',
 'spares',
 'tour',
 'bar',
 'booking',
 'industries',
 'network',
 'blocks',
 'constructing',
 'constructions',
 'material',
 'rose',
 'supply',
 'appliances',
 'color',
 'event',
 'laundry',
 'loading',
 'loom',
 'pharma',
 'solar',
 'sugar',
 'tuition',
 'brands',
 'bricks',
 'components',
 'dental',
 'grill',
 'processing',
 'automobiles',
 'consultant',
 'load',
 'materials',
 'mechanical',
 'passenger',
 'projects',
 'pvc',
 'rice',
 'showroom',
 'stores',
 'tea',
 'bazar',
 'carting',
 'chemical',
 'estate',
 'leather',
 'lighting',
 'stones',
 'tv',
 'vessels',
 'construction',
 'doors',
 'grains',
 'green',
 'kiryana',
 'legal',
 'ornaments',
 'waste',
 'wheat',
 'window',
 'aluminium',
 'application',
 'block',
 'cattle',
 'diesel',
 'distributorsip',
 'equipments',
 'sheet',
 'yard',
 'agricultural',
 'consulting',
 'cosmetics',
 'covering',
 'factories',
 'industries',
 'manufacturer',
 'pipes',
 'stores',
 'tempo',
 'tracks',
 'automobile',
 'banner',
 'clothes',
 'consumer',
 'motors',
 'petrol',
 'powder',
 'pump',
 'vegetables',
 'writer',
 'agriculturist',
 'bore',
 'chips',
 'feed',
 'koil',
 'light',
 'medicals',
 'schools',
 'sea',
 'sofa',
 'borewell',
 'carrier',
 'chemicals',
 'coffee',
 'drinks',
 'medicines',
 'mills',
 'parcel',
 'travels',
 'flooring',
 'kirana',
 'onion',
 'paints',
 'photography',
 'plants',
 'subcontract',
 'wall',
 'buffalo',
 'clinic',
 'eggs',
 'electrician',
 'housing',
 'jewelry',
 'leaf',
 'sports',
 'suit',
 'travels',
 'utensils',
 'bangles',
 'contractors',
 'cooking',
 'cosmetic',
 'farmers',
 'gunny',
 'lunch',
 'milking',
 'rikshaw',
 'wiring',
 'batteries',
 'cafe',
 'ceramic',
 'courier',
 'feeds',
 'garden',
 'garments',
 'gym',
 'jewellery',
 'metals',
 'milk',
 'oil',
 'park',
 'parties',
 'plates',
 'rewinding',
 'soft',
 'solution',
 'suits',
 'articles',
 'cars',
 'cell',
 'cement',
 'delivering',
 'drawing',
 'events',
 'highway',
 'readymade',
 'taxi',
 'battery',
 'binding',
 'colour',
 'dealersip',
 'fire',
 'function',
 'hotels',
 'jewellers',
 'namkeen',
 'recharge',
 'soap',
 'tank',
 'technologies',
 'tex',
 'traders',
 'bazaar',
 'bearing',
 'biscuits',
 'bottles',
 'chairs',
 'confectionery',
 'court',
 'fittings',
 'paint',
 'shirts',
 'spices',
 'sticks',
 'tiffins',
 'windows',
 'woods',
 'yarn',
 'artificial',
 'bags',
 'departmental',
 'diamonds',
 'gate',
 'global',
 'hotel',
 'investment',
 'lorries',
 'materials',
 'plastics',
 'samosa',
 'stall',
 'vegetables',
 'window',
 'wire',
 'birthday',
 'blouse',
 'briyani',
 'buffaloes',
 'chips',
 'crusher',
 'lights',
 'marriages',
 'oils',
 'ornament',
 'plate',
 'press',
 'purifier',
 'rolling',
 'sewing',
 'shed',
 'tailors',
 'windows',
 'bangles',
 'blouses',
 'borewells',
 'bridal',
 'cards',
 'coir',
 'decorator',
 'door',
 'erection',
 'furniture',
 'hospitals',
 'logistics',
 'merchant',
 'ply',
 'precious',
 'salwar',
 'satara',
 'shops',
 'tailor',
 'temples',
 'transport',
 'transporting',
 'wheat',
 'bhel',
 'bike',
 'buses',
 'cab',
 'caterers',
 'colleges',
 'crane',
 'gurukkul',
 'import',
 'imported',
 'internet',
 'jobwork',
 'lace',
 'lodge',
 'marbles',
 'marker',
 'pav',
 'pet',
 'prawns',
 'school',
 'sheets',
 'shirt',
 'shirts',
 'shopping',
 'steels',
 'teaching',
 'workshop',
 'army',
 'buildersamp',
 'constructions',
 'corn',
 'craft',
 'dairy',
 'exports',
 'fabrications',
 'fertilizer',
 'fitness',
 'flowersbusiness',
 'furnitures',
 'marriage',
 'modular',
 'panel',
 'pesticides',
 'pharmacy',
 'practicing',
 'sadi',
 'salon',
 'tinkering',
 'transportation',
 'transports',
 'trucks',
 'tution',
 'accountant',
 'advertising',
 'blouses',
 'booth',
 'brass',
 'cargo',
 'ceiling',
 'chinese',
 'coal',
 'computerized',
 'copper',
 'covers',
 'creation',
 'crop',
 'glass',
 'glasses',
 'grinding',
 'handloom',
 'instruments',
 'ring',
 'rings',
 'scraps',
 'seat',
 'stitches',
 'tiles',
 'wedding',
 'bags',
 'buffaloes',
 'cane',
 'casting',
 'chowk',
 'communication',
 'diary',
 'drives',
 'gear',
 'goat',
 'jewellery',
 'lift',
 'mall',
 'mat',
 'nut',
 'nuts',
 'potato',
 'prints',
 'sarees',
 'silks',
 'steel',
 'table',
 'tailorsfor',
 'thakur',
 'took',
 'traders',
 'trust',
 'tube',
 'van',
 'vegetable',
 'wear',
 'yards',
 'academy',
 'accounting',
 'beautician',
 'boards',
 'boats',
 'button',
 'chains',
 'coating',
 'coconuts',
 'contractors',
 'cutlery',
 'drilling',
 'egg',
 'fashion',
 'franchise',
 'jeans',
 'ladies',
 'mandi',
 'music',
 'natural',
 'organic',
 'peanut',
 'phones',
 'precision',
 'puja',
 'storage',
 'telecom',
 'ticket',
 'transport',
 'vision',
 'arts',
 'ayurvedic',
 'bamboo',
 'bending',
 'biscuits',
 'bread',
 'bubble',
 'buffalo39s',
 'cabs',
 'fitting',
 'franchisee',
 'gate',
 'gram',
 'hall',
 'handicraft',
 'hotel',
 'irrigation',
 'jeans',
 'jute',
 'nursng',
 'palace',
 'printing',
 'soda',
 'sounds',
 'spa',
 'stiching',
 'table',
 'textiles',
 'tobacco',
 'towel',
 'tower',
 'trees',
 'accessories',
 'bag',
 'band',
 'biryani',
 'camera',
 'cast',
 'chillies',
 'cloths',
 'decorations',
 'dj',
 'drugs',
 'eye',
 'factory',
 'festival',
 'fruits',
 'garage',
 'hydraulic',
 'knitting',
 'kripa',
 'lemon',
 'moulding',
 'nasta',
 'packets',
 'parlour',
 'patti',
 'poojas',
 'printers',
 'ricecool',
 'shoes',
 'snacks',
 'studio',
 'tools',
 'toys',
 'wastage',
 'aavin',
 'agents',
 'beedi',
 'boards',
 'boxes',
 'chat',
 'china',
 'chocolate',
 'clothing',
 'coffee',
 'collection',
 'components',
 'compound',
 'cook',
 'cranes',
 'crockery',
 'cutter',
 'dance',
 'drinking',
 'driver',
 'dying',
 'fabric',
 'fashions',
 'fixing',
 'foam',
 'furnishing',
 'garlic',
 'generator',
 'hospital',
 'iron',
 'jasmine',
 'jewels',
 'lic',
 'lights',
 'meals',
 'merchants',
 'meter',
 'milks',
 'mines',
 'mobil',
 'movers',
 'photos',
 'police',
 'puri',
 'restaurant',
 'shed',
 'shirts',
 'stationery',
 'tanks',
 'tmt',
 'transport',
 'watch',
 'animal',
 'architect',
 'bakery',
 'batteries',
 'betel',
 'builder',
 'cashew',
 'construction',
 'corrugated',
 'cultivation',
 'cyber',
 'depot',
 'designs',
 'die',
 'distributors',
 'doors',
 'drainage',
 'dress',
 'drill',
 'fishes',
 'fuel',
 'functions',
 'goats',
 'graphics',
 'gray',
 'lamination',
 'lathe',
 'engineers',
 'engineer',
 'loads',
 'engineering',
 'manufacturing',
 'job',
 'salary',
 'salaried']

In [16]:
### CONVERTING TO LOWER CASE
R_data['customer business']=R_data['customer business'].str.lower()

In [17]:
### Removing Punctuation
R_data['customer business'] = R_data['customer business'].str.replace('[^\w\s]','')
R_data['customer business'].head()

0    applicant is running a tuition centre in the n...
1     profile wise applicant is into fishering busi...
2    customer is running a degree colleges by the n...
3    \tcustomer is into whole sale trading of ladie...
4    mr uday dighe is into business of interior wor...
Name: customer business, dtype: object

In [18]:
### REMOVING UNWANTED SPACE
R_data['customer business'] = R_data['customer business'].replace('\s+', ' ', regex=True)
R_data['customer business'].head()

0    applicant is running a tuition centre in the n...
1     profile wise applicant is into fishering busi...
2    customer is running a degree colleges by the n...
3     customer is into whole sale trading of ladies...
4    mr uday dighe is into business of interior wor...
Name: customer business, dtype: object

In [19]:
R_data['customer business']=R_data['customer business'].astype(str)

In [ ]:
#### lemmatization
# from textblob import Word
# R_data['customer business'] = R_data['business'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
# R_data['customer business'].head()

In [ ]:
# raw_data=str(R_data['customer business'])
# raw_data

In [ ]:
# R_data=R_data.dropna(subset=['Critical Observation']) 
# R_data.shape

In [ ]:
# s=R_data[['Lead.ID','customer business keywords','customer business']]
# s.to_csv('D:/HL/identifying_customer_business.csv',index=False)

In [ ]:
# R_data[R_data['Critical Observation'].apply(lambda x: x in Dict['Key Words']).tolist()]

In [ ]:
# f = lambda x: len(x['Key Words'].split(['Critical Observation'])) -1
# R_data['Critical Observation'] = R_data.apply(f, axis=1)

In [ ]:
# df = R_data[R_data["Critical Observation"].str.contains("sign")]

In [ ]:
# R_data['customer business']=R_data['customer business'].astype(str)

In [ ]:
# vv=re.split('(.*).coapplicant.(.*)',R_data['customer business'][23])
# vv

In [20]:
cols = 'applicant coapplicant'.split()
R_data[cols]=R_data['customer business'].str.extract('(.*).(coapplicant..*)', expand=True)

In [21]:
R_data.head()

,Lead.id,customer business,applicant,coapplicant
0,53f032d3-0830-4025-a,applicant is running a tuition centre in the n...,applicant is running a tuition centre in the n...,coapplicant applicant39s spouse is also 35 yea...
1,246dfdcc-0f24-4f19-8,profile wise applicant is into fishering busi...,profile wise applicant is into fishering busi...,coapplicant is mrs jesima age46 yrs is spouse ...
2,9c1b8078-d323-47d6-8,customer is running a degree colleges by the n...,NaN,NaN
3,91d81bfe-953a-4667-8,customer is into whole sale trading of ladies...,NaN,NaN
4,4d39cb27-ba85-475d-a,mr uday dighe is into business of interior wor...,mr uday dighe is into business of interior wor...,coapplicant mrs vaibhavi dighe is running a ve...

In [22]:
R_data['applicant']=np.where(R_data['applicant'].isnull(), R_data['customer business'],R_data['applicant'])

In [23]:
R_data['applicant']=R_data['applicant'].astype(str)

In [ ]:
# matches = regex.findall(pattern,y, regex.IGNORECASE)
# matches = set(map(str.lower, regex.findall(pattern, y, regex.IGNORECASE)))

In [24]:
data=[]
pattern = r'\b({})\b'.format('|'.join(map(regex.escape, L_Dict)))
# unique matches, lowercased
for y in  R_data['applicant']:
#         print(y)
        matches = regex.findall(pattern,y, regex.IGNORECASE)
#         temp = [x.upper() for x in L_Dict if x.lower() in matches]
#         print(temp)  # ['TEST', 'MULTIPLE', 'MATCH']
        
        data.append(matches)
print(len(data))
R_data['Applicant business']=data

11634

In [25]:

R_data['coapplicant']=R_data['coapplicant'].astype(str)

In [26]:
data=[]
pattern = r'\b({})\b'.format('|'.join(map(regex.escape, L_Dict)))
# unique matches, lowercased
for y in  R_data['coapplicant']:
#         print(y)
        matches = regex.findall(pattern,y, regex.IGNORECASE)
#         temp = [x.upper() for x in L_Dict if x.lower() in matches]
#         print(temp)  # ['TEST', 'MULTIPLE', 'MATCH']
        
        data.append(matches)
print(len(data))
R_data['Co_applicant_business']=data

11634

In [94]:
# R_data.head()

In [95]:
def getUniqueItems(iterable):
    seen = set()
    result = []
    for item in iterable:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result

In [96]:
dup=R_data['Applicant business'].tolist()
results = []
for ak in dup:
    hj=getUniqueItems(ak)
    results.append(hj)
R_data['Business_of_applicant']=  results

In [97]:
b1=[]
b2=[]
for y in  R_data['Business_of_applicant']:
    first=' '.join(y)
    splitted = first.split()
    b1_split=splitted[:3]
    b2_split=splitted[3:]
    b1.append(b1_split)
    b2.append(b2_split)
print(len(data))
R_data['First_business']=b1
R_data['Second_business']=b2

11634

In [29]:
d2= pd.read_csv("D:/HL/business_kw.csv",encoding = "ISO-8859-1")

In [30]:
d2['Profile']=d2['Profile'].str.lower()

In [31]:
d2=d2.drop_duplicates()

In [99]:
b3=[]
for y in  R_data['First_business']:
    business=' '.join(y)
    b3.append(business)
R_data['First_business_2']=b3

In [33]:
d2=d2['Profile'].tolist()

In [34]:
data=[]
pattern = r'\b({})\b'.format('|'.join(map(regex.escape, d2)))
# unique matches, lowercased
for y in  R_data['First_business_2']:
#         print(y)
        matches = regex.findall(pattern,y, regex.IGNORECASE)
#         temp = [x.upper() for x in L_Dict if x.lower() in matches]
#         print(temp)  # ['TEST', 'MULTIPLE', 'MATCH']
        
        data.append(matches)
print(len(data))
R_data['Identified_business']=data

11634

In [120]:
R_data.head()

,Lead.id,customer business,applicant,coapplicant,Applicant business,Co_applicant_business,First_business,Second_business,First_business_2,Identified_business,Business_of_applicant,Business_of_applicant_all
0,53f032d3-0830-4025-a,applicant is running a tuition centre in the n...,applicant is running a tuition centre in the n...,coapplicant applicant39s spouse is also 35 yea...,"[tuition, tuition, tuition, classes, schools, ...","[rented, tuition]","[tuition, classes, schools]","[school, drawing, rented, power, salary, rental]",tuition classes schools,[],"[tuition, classes, schools, school, drawing, r...",tuition classes schools school drawing rented ...
1,246dfdcc-0f24-4f19-8,profile wise applicant is into fishering busi...,profile wise applicant is into fishering busi...,coapplicant is mrs jesima age46 yrs is spouse ...,"[boat, boat, fish, self, housing, housing, gold]",[school],"[boat, fish, self]","[housing, gold]",boat fish self,[],"[boat, fish, self, housing, gold]",boat fish self housing gold
2,9c1b8078-d323-47d6-8,customer is running a degree colleges by the n...,customer is running a degree colleges by the n...,nan,"[colleges, education, schools, college, school...",[],"[colleges, education, schools]","[college, school, yards, self]",colleges education schools,[],"[colleges, education, schools, college, school...",colleges education schools college school yard...
3,91d81bfe-953a-4667-8,customer is into whole sale trading of ladies...,customer is into whole sale trading of ladies...,nan,"[trading, ladies, garments, garments, traders,...",[],"[trading, ladies, garments]","[traders, job, salary]",trading ladies garments,[],"[trading, ladies, garments, traders, job, salary]",trading ladies garments traders job salary
4,4d39cb27-ba85-475d-a,mr uday dighe is into business of interior wor...,mr uday dighe is into business of interior wor...,coapplicant mrs vaibhavi dighe is running a ve...,"[interior, furniture, operates, enterprises, j...","[vegetable, shop, rented, daily, rental, renta...","[interior, furniture, operates]","[enterprises, job, material, projects, road, t...",interior furniture operates,[furniture],"[interior, furniture, operates, enterprises, j...",interior furniture operates enterprises job ma...

In [119]:
b3=[]
for y in  R_data['Business_of_applicant']:
    business=' '.join(y)
    b3.append(business)
R_data['Business_of_applicant_all']=b3

In [121]:
R_data.to_csv('D:/HE_Bounce_prediction/HE_approval_note/Applicant_coapplicant_business_information.csv',index=False)

In [102]:
# function for calculating the frequency 
def freq(str): 
  
    # break the string into list of words 
    str_list = str.split() 
  
    # gives set of unique words 
    unique_words = set(str_list) 
      
    for words in unique_words : 
        print(words , ':',str_list.count(words))

In [122]:
pd.set_option("display.max_rows", None)